services:

  frontend:
    environment:
      SPA_CONFIG_URLS: /openmrs/spa/configs/config.json

  env-substitution:
    environment:
      - ODOO_PUBLIC_URL=http://${ODOO_HOSTNAME}

  odoo:
    environment:
      - ADDONS=sale_management,stock,account_account,purchase,mrp,mrp_product_expiry,product_expiry,l10n_generic_coa,odoo_initializer,ozone_settings,auth_oidc,web_company_color

  openmrs:
    volumes:
      - "${DISTRO_PATH}/binaries/openelis/truststore:/etc/openelis-global/truststore"
      - "${DISTRO_PATH}/binaries/openelis/keystore:/etc/openelis-global/keystore"